/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ProcessedBlog } from "./ProcessedBlog";
import { ProcessedBlogCountArgs } from "./ProcessedBlogCountArgs";
import { ProcessedBlogFindManyArgs } from "./ProcessedBlogFindManyArgs";
import { ProcessedBlogFindUniqueArgs } from "./ProcessedBlogFindUniqueArgs";
import { DeleteProcessedBlogArgs } from "./DeleteProcessedBlogArgs";
import { ProcessedBlogService } from "../processedBlog.service";
@graphql.Resolver(() => ProcessedBlog)
export class ProcessedBlogResolverBase {
  constructor(protected readonly service: ProcessedBlogService) {}

  async _processedBlogsMeta(
    @graphql.Args() args: ProcessedBlogCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ProcessedBlog])
  async processedBlogs(
    @graphql.Args() args: ProcessedBlogFindManyArgs
  ): Promise<ProcessedBlog[]> {
    return this.service.processedBlogs(args);
  }

  @graphql.Query(() => ProcessedBlog, { nullable: true })
  async processedBlog(
    @graphql.Args() args: ProcessedBlogFindUniqueArgs
  ): Promise<ProcessedBlog | null> {
    const result = await this.service.processedBlog(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProcessedBlog)
  async deleteProcessedBlog(
    @graphql.Args() args: DeleteProcessedBlogArgs
  ): Promise<ProcessedBlog | null> {
    try {
      return await this.service.deleteProcessedBlog(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
